Fix IntegrityError when user has multiple email addresses
Banno/getsentry-ldap-auth pull request #29
Opened 2018-01-14 10:11 UTC by ralphje

Since you can set up multiple email addresses for users, it is possible that sentry_ldap_auth updates the wrong email address when changing the UserEmail field. 

Say, you have two UserEmail objects for an user, 'personal' and 'system-wide'. When 'personal' gets updated to "system-wide", this generates an IntegrityError because (user, email) is unique in the database, preventing logon.

Instead of changing the attribute, I add it to the list of the user's email addresses. There's no reliable way to remove an old email address.

I doubt this entire structure is even necessary because when the 'email' attribute is set correctly on ``AUTH_LDAP_USER_ATTR_MAP`` this should all happen automatically.

2018-04-19 14:50 UTC, aleksihakli requested changes
I think a small fix should be made to improve backwards compatibility. The `django.db.models.Q` object should be available in Django 1.6+, meaning the Sentry Django installation should have it.

2018-04-19 14:50 UTC, aleksihakli commented on sentry_ldap_auth/backend.py
> +                email = ''
This changes the currently "empty" getsentry-ldap-auth email from `' '` to `''`, possibly leaving dangling database rows with `email=' '`.

2018-04-19 14:50 UTC, aleksihakli commented on sentry_ldap_auth/backend.py
> +            UserEmail.objects.filter(user=user, email='').delete()
This should be something like

```python
from django.models import Q

# ...

UserEmail.objects.filter(user=user, Q(email='') | Q(email=' ')).delete()
```

2018-04-19 15:04 UTC, aleksihakli commented
@barronhagerman is it possible to get this baked into a new release, e.g. 2.6? We have ongoing issues with users inputting custom emails and failing authentication over LDAP afterwards.

2018-04-20 21:47 UTC, barronhagerman approved these changes
Sorry I'm just getting around to this. I don't have the problem you've described, and I don't have a good environment to test it. However, I do think this should fix it without breaking something else. I'll try to get a release cut next week with this and the updates @aleksihakli brought up.

2018-04-20 21:48 UTC, merged